### PR TITLE
Remove xenlight backend

### PR DESCRIPTION
**Pull request by jonludlam**
It's not being maintained in any meaningful way.

Signed-off-by: Jon Ludlam <jonathan.ludlam@citrix.com>

### CODE REVIEW

**Comment by jonludlam** [comment]
Don't merge until we've got the spec file fixes.

**Comment by robhoes** [comment]
😮

**Comment by mseri** [comment]
😱

**Comment by johnelse** [comment]
:astonished:

**Comment by mseri** [comment]
@jonludlam what will your ARM board do now? Are you splitting out the package?

**Comment by lindig** [comment]
I have prepared an updated `xenopsd.spec` that probably should be merged first.

**Comment by lindig** [comment]
This requires various changes in internal repos that build the product. Don't merge this yet.

**Pull request merged**
