### PR TITLE
Rebase master branch to qemu-upstream branch

### PR DESCRIPTION
**Pull request by fillzero**
For upstream QEMU feature, given the whole xenserver-spec feature repo has been rebased, so I need to rebase this repo to fix build error.

### CODE REVIEW

**Comment by fillzero** [comment]
@mseri Would you please help to check and merge? Thanks a lot.

**Comment by fillzero** [comment]
Build error log:
```
File "xc/device.ml", line 613, characters 37-52:
Error: This expression has type 'a * 'b
       but an expression was expected of type string
```
Because the code change depends on the latest ocaml-qmp, which seems has not been released.

**Comment by mseri** [comment]
I don't think I am the right person for this. Ping @Frezzle or @gaborigloi, is it possible to use the xenserver-build-env to use the custom rpms from the qemu-upstream branch for this branch?

**Comment by gaborigloi** [comment]
@mseri @fillzero yes, we can create a Travis setup if there is a feature branch that we can use as the source of the RPMs. I couldn't find any such feature branch though.

**Comment by fillzero** [comment]
@gaborigloi @mseri -- 
Sorry, I'm wrong. I should not send pull request to rebase feature branch. 
I will find @huizh to rebase this feature branch to master.
Cancel this PR.

**Pull request closed without merging**
