### PR TITLE
Add linker option -L/lib64 -lxentoollog to fix Opam build

### PR DESCRIPTION
**Pull request by lindig**
This commit adds a linker flag in _oasis to help the linker find libxentoollog when compiling in an Opam workflow (opam install xapi-xenopsd). The remaining commits introduce changes in auto-generated files and fix whitespace issues in _oasis. These changes were tested in an RPM build.

Signed-off-by: Christian Lindig <christian.lindig@citrix.com>

### CODE REVIEW

**Comment by gaborigloi** [comment]
We had to do a similar thing for `xenctrl` (ocaml-xen-lowlevel-libs), and older versions of xen did not compile with the `-lxentoollog` linker flag: https://github.com/xapi-project/ocaml-xen-lowlevel-libs/pull/99

**Comment by lindig** [comment]
I can make this optional in the _oasis file, too, and take a look at the configuration code.

**Comment by gaborigloi** [comment]
It depends on whether we want to support xen versions < 4.7, I think the `-lxentoollog` flag would cause an error for older xen versions that don't have this shared library (at least in the Ubuntu packages: http://packages.ubuntu.com/search?keywords=libxen-dev&searchon=names&suite=all&section=all )

**Comment by mseri** [comment]
I think we should make its use automatic in a similar fashion as in ocaml-xen-lowlevel-libs

**Comment by gaborigloi** [comment]
I think we would have to copy the code that detects the version of xen from [`ocaml-xen-lowlevel-libs`](https://github.com/xapi-project/ocaml-xen-lowlevel-libs) :(. I don't really know why the libxentoollog.so/.a file is missing from earlier Ubuntu packages.

**Comment by mseri** [comment]
Yes. We could use a `c` program that links to `xentoollog` and check if it succeds (mocking the `find_xen_*` in `config.ml` there.

**Comment by lindig** [comment]
Closing this - it needs some more work to make the linking optional.

**Pull request closed without merging**
