### PR TITLE
introduce nic_type as a configuration option .

### PR DESCRIPTION
**Pull request by anshulmakkar**
@andyhhp : Please review the patch. I have addressed your comments.

### CODE REVIEW

**Comment by anshulmakkar** [comment]
@andyhhp : please can you re-comment on the patch.

**Comment by anshulmakkar** [comment]
@andyhhp : Please can you review the latest commit 76c6387.

**Comment by robhoes** [comment]
Please add a signed-off-by line to the commit message.

**Comment by robhoes** [comment]
@anshulmakkar ⬆️

**Comment by anshulmakkar** [comment]
@robhoes : I have added signed-off-by tag. Please merge the pull request or let me know if I have to raise a separate request for merge.

**Comment by robhoes** [comment]
Thanks Anshul.

**Pull request merged**
