### PR TITLE
CP-36452: Backport QEMU 4.2 to Yangtze

### PR DESCRIPTION
**Pull request by anthonyper-ctx**
These are command line changes to be able to use QEMU 4.2.
There's also a change to the SPEC file.

### CODE REVIEW

**Comment by psafont** [comment]
@robhoes should a new lcm branch be created for this?

**Comment by lindig** [comment]
We have tagged up to `v0.150.5` for hotfixes. We could simply merge this into the `0.150-lcm` branch and only branch once we are forced to do it - and so avoid having potentially diverging branches.

**Review by edwintorok — APPROVED** [review]
I checked that this matches the below commands, and looking through git commit messages I didn't find any other commit referencing qemu between 0.150-lcm and HEAD:
```
git checkout 0.150-lcm
git pull
git cherry-pick 7fda4fd
git cherry-pick 84a707b
git cherry-pick a7f43e1
git cherry-pick f30a25e
```

**Comment by psafont** [comment]
> We have tagged up to v0.150.5 for hotfixes. We could simply merge this into the 0.150-lcm branch and only branch once we are forced to do it - and so avoid having potentially diverging branches.

We might need to change the stockholm branch from xs-opam to stop following that branch (and set up one for this release)

**Review by psafont — APPROVED** [review]

**Comment by edwintorok** [comment]
Discussed with @anthonyper-ctx that this has passed some testing, and is ready for submission now. Merging and going to tag.

**Pull request merged**
