### PR TITLE
memory_server: Remove unused file

### PR DESCRIPTION
**Pull request by euanh**
This file is now in squeezed.

Signed-off-by: Euan Harris <euan.harris@citrix.com>

### CODE REVIEW

**Comment by euanh** [comment]
@xen-git: Retest this please.

**Comment by johnelse** [comment]
Is it correct to change the exception we're handling here? I think the correct thing to do would be to get `EEXIST` into upstream xenstore (not trivial I know).

**Comment by euanh** [comment]
@johnelse: Good point.   Our package definitions say that we use mirage's ocaml-xenstore, but internally we sync from xapi-project's fork.   @jonludlam reckoned that we should probably switch to a release of mirage's xenstore, as new development seems to be happening there.

**Comment by euanh** [comment]
@xen-git: Retest this please.

**Pull request merged**
