### PR TITLE
Use `xl pci-attach` for HVM guests

### PR DESCRIPTION
**Pull request by simonjbeaumont**

### CODE REVIEW

**Comment by robhoes** [comment]
Hmm.... I see that add_noexn actually ignored the `msitranslate` argument and set `msitranslate=0`. And xenopsd_server_xc put the value in xenstore itself... Probably ok then.

**Comment by robhoes** [comment]
@simonjbeaumont Both test builds failed...

**Comment by simonjbeaumont** [comment]
Built for me... :(

**Comment by simonjbeaumont** [comment]
@xen-git retest this please.

**Comment by simonjbeaumont** [comment]
We should probably further prune the arguments (including `msitranslate`) since they're being ignored by `add_xl` anyway.

**Comment by simonjbeaumont** [comment]
@robhoes updated.

**Comment by robhoes** [comment]
:shipit:

**Pull request merged**
