### PR TITLE
CP-23986: Implement epoll

### PR DESCRIPTION
**Pull request by fillzero**
Implement epoll

Signed-off-by: Liang Dai <liang.dai1@citrix.com>

### CODE REVIEW

**Comment by fillzero** [comment]
https://github.com/xapi-project/xenopsd/pull/377 depends on this PR

**Comment by robhoes** [comment]
Couple of points:
* There are very similar bindings for poll (not epoll) in xl/.
* I prefer to use ctypes for new bindings.
* Isn't there a third-party library that has such bindings? We can't be the only ones who need this.

**Comment by lindig** [comment]
Where is this code coming from? The C code has no copyright and is new.

**Comment by fillzero** [comment]
Thanks, I will change code follow pattern like `xl/poll_stubs.c`, will update code later.
If ring3 prefer third-party library, I can try to use `Linux_ext.Epoll` in https://github.com/xapi-project/xenopsd/pull/377

https://ocaml.janestreet.com/ocaml-core/109.23.00/doc/core/Linux_ext.Epoll.html

**Comment by lindig** [comment]
* The JaneStreet core library is copyrighted
* The JaneStreet core library is already part of xs-opam: https://github.com/xapi-project/xs-opam/tree/master/packages/upstream/core.113.33.03

**Comment by mseri** [comment]
`Epoll` is also in `core.113`: https://ocaml.janestreet.com/ocaml-core/113.33/doc/core/Linux_ext_intf/S.modt/Epoll.mod/

**Comment by fillzero** [comment]
Thanks, I'm trying to use Linux_ext.Epoll (version: core.113), will update PR later.

**Comment by fillzero** [comment]
Hi, I submitted a new  PR https://github.com/xapi-project/xenopsd/pull/378 using `Linux_ext.Epoll`.
Shall we close this one?
Add @mg12

**Comment by fillzero** [comment]
Closed in favour of https://github.com/xapi-project/xenopsd/pull/378

**Pull request closed without merging**
