### PR TITLE
CP-10531: Add device in guest_agent.

### PR DESCRIPTION
**Pull request by huizh**
Add device in guest_agent for xapi to handle.

Signed-off-by: Hui Zhang <hui.zhang@citrix.com>

### CODE REVIEW

**Comment by robhoes** [comment]
@xen-git Re-test this please.

**Comment by robhoes** [comment]
@huizh The patch looks fine, but it would be useful to briefly explain the purpose of it in the commit message.

**Comment by huizh** [comment]
Thanks @robhoes. 
I've added more description in the commit message.

**Comment by robhoes** [comment]
@huizh, thanks, I'll merge this now.

**Comment by huizh** [comment]
@robhoes thank you.

**Pull request merged**
