### PR TITLE
CP-25344: Moved the qemu-wrapper script in to the xenopsd repo.

### PR DESCRIPTION
**Pull request by kc284**
Signed-off-by: Konstantina Chremmou <konstantina.chremmou@citrix.com>

### CODE REVIEW

**Comment by rosslagerwall** [comment]
This looks generally OK to me. Please ensure that the qemu-wrapper script is the latest one from the qemu.pg repo so that no changes are missed.

Obviously you'll also need a corresponding change to remove the script from qemu.pg otherwise there will be two RPM packages trying to own /usr/lib64/xen/bin/qemu-wrapper.

**Comment by kc284** [comment]
@rosslagerwall At the time of writing the script is the latest one (at 80df3dba8a0).
There will be another two PRs to modify the specs and the patchqueue respectively, but I'm waiting for the current PR to be merged and the repo to be tagged first.

**Comment by mseri** [comment]
There is no need to tag this repo, as xenopsd is pinned in the feature branch. Just make a PR where you bump the release and make the necessary specfile changes in the meanwhile, and mention that it is blocked until this is merged

**Comment by kc284** [comment]
I've made the change (will squash the commits when we're ready for merging).

**Comment by mseri** [comment]
Feel free to squash and merge

**Pull request merged**
