### PR TITLE
CA-227101: Increase timeout from 0 to 60 seconds when squeezing domains.

### PR DESCRIPTION
**Pull request by sharady**
Add missing fix for CA-92842.

Signed-off-by: Sharad Yadav <sharad.yadav@citrix.com>

### CODE REVIEW

**Comment by sharady** [comment]
This fix need to be merged only after Ely is branched out from trunk.

**Comment by lindig** [comment]
Could you extend the commit message? Without context, it looks like you fixed a typo by moving it from 0 to 60 seconds. This could also go into the subject line: `CA-227101: Increase timeout to 60s when squeezing domains`,

**Comment by jonludlam** [comment]
There's some additional context here: https://github.com/xapi-project/xen-api/pull/1262 - essentially it was indeed a typo.

**Comment by sharady** [comment]
@lindig  @jonludlam Thanks for the suggestion, I have updated the commit message.

**Pull request merged**
