### PR TITLE
CA-351823 UPD-678 [@sexp.option] fix

### PR DESCRIPTION
**Pull request by lippirk**

### CODE REVIEW

**Comment by robhoes** [comment]
So this problem does not exist on `master`, because we use a newer version of sexplib?

**Comment by edwintorok** [comment]
Do we use @sexp.option anywhere else on Stockholm?

**Comment by lippirk** [comment]
> So this problem does not exist on `master`, because we use a newer version of sexplib?

Yes - the problem also doesn't exist on havana, because we're still using `sexp_option` there:
https://github.com/xapi-project/xenopsd/blob/0.17-lcm/lib/suspend_image.ml

**Comment by lippirk** [comment]
> Do we use @sexp.option anywhere else on Stockholm?

Probably not, since doing a search on github yields only this instance: https://github.com/search?q=org%3Axapi-project+%5B%40sexp.option%5D&type=code

**Review by robhoes — APPROVED** [review]
Good catch!

**Review by lindig — APPROVED** [review]

**Pull request merged**
