### PR TITLE
CP-29100: Remove PCI Device and expose IO port for communication with varstored.

### PR DESCRIPTION
**Pull request by ndavison21**
Changes to arguments passed to varstored.

### CODE REVIEW

**Comment by edwintorok** [comment]
I think you have a typo in the commit message and missing an initial C in CP. Also please add a Signed-off-by line to all commits submitted to open source projects: https://wiki.xenproject.org/wiki/Submitting_Xen_Project_Patches#Signing_off_a_patch

**Comment by ndavison21** [comment]
Fixed

**Comment by edwintorok** [comment]
Can we merge this now, or does this depend on a corresponding change in varstored?

**Comment by ndavison21** [comment]
There are corresponding changes in review for varstored and edk2, so best to wait.

**Comment by ndavison21** [comment]
This can be merged now

**Comment by ndavison21** [comment]
this can be merged now

**Comment by ndavison21** [comment]
this can be merged now

**Pull request merged**
