### PR TITLE
[CA-155888] remove reservation id after domain build completes

### PR DESCRIPTION
**Pull request by Chunjie**
Signed-off-by: Chunjie Zhu <chunjie.zhu@citrix.com>

### CODE REVIEW

**Comment by Chunjie** [comment]
add @djs55 to review

**Comment by xen-git** [comment]
Can one of the admins verify this patch for testing?

**Comment by djs55** [comment]
This looks fine.

**Comment by jonludlam** [comment]
Thanks @Chunjie !

**Pull request merged**
