### PR TITLE
CP-14345 - Don't apply a CPUID policy.  Xenguest does this already

### PR DESCRIPTION
**Pull request by andyhhp**

### CODE REVIEW

**Comment by johnelse** [comment]
Thanks - please add a signed-off-by line to the commit message.

**Comment by xen-git** [comment]
Can one of the admins verify this patch for testing?

**Comment by andyhhp** [comment]
Oops sorry - ammended

**Comment by johnelse** [comment]
@xen-git test this please

**Comment by robhoes** [comment]
This is going to a feature branch. The test build will probably fail because there are changes to xcp-idl in the branch. We'll ignore that. The patch looks fine otherwise.

**Comment by johnelse** [comment]
Any reason not to remove Domain.cpuid_apply as well, given this is the only place it's called?

**Comment by andyhhp** [comment]
I suspect that all the cpuid bits in xc/domain.ml can go.  Quite a lot of it appears to be orphaned.

However, I am currently fighting with opam to actually compile xenopsd, and I need this specific fix to prevent xenopsd from clobbering the cpuid policy developed by Xenguest

**Comment by robhoes** [comment]
I'll do a cleanup later on.

**Comment by johnelse** [comment]
Ok :+1:

**Comment by robhoes** [comment]
I'm going to merge this now...

**Pull request merged**
