### PR TITLE
Use serial_list rather than serial.

### PR DESCRIPTION
**Pull request by jonludlam**
The bindings are currently generating an empty list for serial_list
which fails when a serial value is set too. One possible fix is to
use a string list option type. This works around the problem for now.

Signed-off-by: Jon Ludlam <jonathan.ludlam@citrix.com>

### CODE REVIEW

**Comment by jonludlam** [comment]
@djs55 what's your opinion on this? We could put the patch into xen-api-libs-specs instead of committing here? I don't really want to break the build on xen 4.4

**Comment by jonludlam** [comment]
@xen-git retest this please

**Comment by djs55** [comment]
Looks reasonable to me...

**Comment by djs55** [comment]
Let's auto detect in the style of ocaml-xen-lowlevel-libs i.e. something like
- generate a temp file using the new xenlight field
- run ocamlc and check for non-zero exit code

**Comment by robhoes** [comment]
This optcomp stuff looks really retro dude.

**Comment by jonludlam** [comment]
OK, autodetecting now. Obj.magic ftw!

**Comment by djs55** [comment]
:rocket: let's go (merge)

**Comment by djs55** [comment]
Travis needs a general update - #189

**Pull request merged**
