### PR TITLE
[CA-155888] remove reservation id after domain build completes

### PR DESCRIPTION
**Pull request by Chunjie**
Signed-off-by: Chunjie Zhu <chunjie.zhu@citrix.com>

### CODE REVIEW

**Comment by xen-git** [comment]
Can one of the admins verify this patch for testing?

**Comment by Chunjie** [comment]
add @djs55 to review

**Comment by johnelse** [comment]
@Chunjie I'll leave the code review to @djs55 , but will point out that a lot of the new lines of code are indented with mixed tabs and spaces. Please try to mix the surrounding indentation style (and yes, I know some of the existing code is not always consistent here :) ).

**Comment by Chunjie** [comment]
@johnelse, thanks for the suggestions, I will re-organize code indent and re-submit my patch.

**Comment by samoht** [comment]
@johnelse any plan to `ocp-indent` all of your codebase ? :-)

**Comment by Chunjie** [comment]
re-organize code indent and re-submit pull-request

**Comment by djs55** [comment]
I'll try to review the squeezed patches today!

(I would like to 'ocp-indent' by default, perhaps we should have a
discussion on xen-api)

On Tuesday, March 17, 2015, Chunjie <notifications@github.com> wrote:

> re-organize code indent and re-submit pull-request
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xapi-project/xenopsd/pull/170#issuecomment-82103360>.
>


-- 
Dave Scott

**Comment by Chunjie** [comment]
Hi @djs55,

thanks.

**Comment by Chunjie** [comment]
Hi @djs55,

I re-submit this pull-request, the new pull request is https://github.com/xapi-project/xenopsd/pull/172.

**Pull request closed without merging**
