### PR TITLE
[DO NOT MERGE] CA-286115: xenops_server_xen: add mutex to protect domain_watches update

### PR DESCRIPTION
**Pull request by mseri**
It is still unclear to me if these can run in different threads or not, if they are sycronous the mutex should not add too much overhead.
There are reads in the `watch_fired` function but those should be fine.

Signed-off-by: Marcello Seri <marcello.seri@citrix.com>

### CODE REVIEW

**Comment by mseri** [comment]
This is only for discussion. Do not merge now. At the moment I still believe this PR is not needed.

**Comment by YarsinCitrix** [comment]
Not experience enough to comments whether there could be scenario to have the functions impacted here to run in different threads; but if we assume there is, as the code change intended, theoretically, the mutex have to be used to guard the all of the use (read and write) in one function for data consistency; otherwise, the reads and writes in one function could be different data, as in domain_disappeared and remove_device_watch.

**Comment by mseri** [comment]
Yes, I agree with you. And I think we may have a similar issue if the DB.exist calls are happening in a separate thread as the one that updates the DB. So also there we may need to cover the reads behind the same mutex as the writes

**Comment by jonludlam** [comment]
I believe that there really is only one thread that is responding to xenstore watches so we really don't need these mutexes.

**Pull request closed without merging**
