### PR TITLE
CP-15745: Use xenserver-build-env for travis build

### PR DESCRIPTION
**Pull request by johnelse**

### CODE REVIEW

**Comment by johnelse** [comment]
Something going wrong here:

```
$ export REPO_TEST_CMD=make`
```

**Comment by johnelse** [comment]
```
++ make test
make: Nothing to be done for `test'.
```

:( There are a bunch of test programs in the repo; I'll see if can wrangle them into something `make test` can run.

**Comment by simonjbeaumont** [comment]
@johnelse yeah, it's a bit pants that `make test` isn't doing anything.

**Comment by johnelse** [comment]
I think this is ready to go now. I've removed `make test` from the build steps entirely. All the remaining test programs either need xenstore or xenops-cli to function.

**Pull request merged**
