### PR TITLE
[CA-275746] Build + install fence.bin

### PR DESCRIPTION
**Pull request by mcintyre94**
- Move fence.ml into a subdirectory of xc, xc/fence
- Add a new jbuild file to build fence.bin from fence.ml
- After this we get _build/install/default/bin/fence.bin built
- Add optdir = /opt/xensource/bin to configure.ml
- Install fence.bin to /opt/xensource/bin
- Must be merged with a corresponding change to add this file in xenopsd.spec

Signed-off-by: Callum McIntyre <callum.mcintyre@citrix.com>

### CODE REVIEW

**Comment by mseri** [comment]
Why `.bin` an not `.exe`?

**Comment by edwintorok** [comment]
[XAPI](https://github.com/xapi-project/xen-api/blob/master/scripts/fence)'s script is looking for `.bin`

**Comment by mcintyre94** [comment]
Specifically:
```
[root@bimmer-m4 ~]# cat /opt/xensource/libexec/fence
#!/bin/sh

# Do not use the ocaml XIU stuff for this -- we want the real
# hypervisor to fence this domain.
unset XIU
/opt/xensource/libexec/fence.bin $*
```

**Comment by mseri** [comment]
Do not merge until the spec file change is ready

**Comment by edwintorok** [comment]
We should merge this on monday, lets not break the  build now

**Pull request merged**
